[manifest]
version = "0.6.7"
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "attention_text({"
position = "before"
payload = '''
if G and G.P_CENTERS and G.P_CENTERS.j_mahrlatr_vahrgskelethor_joel then
    local card = G.P_CENTERS.j_mahrlatr_vahrgskelethor_joel
    if not card.unlocked then
        unlock_card(card)
    end
end
'''
match_indent = true